CREATE TABLE IF NOT EXISTS `syncs` (
  `EndTime` DATETIME NULL,
  `Id` VARCHAR(32) NOT NULL,
  `StartTime` DATETIME NOT NULL,
  PRIMARY KEY (`Id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
