on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v4
        with:
          node-version: 18.17.x
      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.x
      - run: dotnet publish -r linux-x64
      - run: echo "${{secrets.EC2_KEY}}" > mk8.pem
      - run: scp -i "mk8.pem" -r "Web/bin/Release/net8.0/linux-x64/publish" ec2-user@16.170.153.81:/home/ec2-user/mk8/web
