on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v4
        with:
          node-version: 18.17.x
      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.x
      - run: dotnet build
